# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='showtime.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eshowtime.proto\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x18\n\x06Movies\x12\x0e\n\x06movies\x18\x01 \x03(\t\"/\n\x0fMoviesSchedules\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\n\n\x08\x45mptyMsg2]\n\x08Showtime\x12/\n\x0cGetListTimes\x12\t.EmptyMsg\x1a\x10.MoviesSchedules\"\x00\x30\x01\x12 \n\x0eGetMovieByDate\x12\x05.Date\x1a\x07.Moviesb\x06proto3'
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='Date.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=38,
)


_MOVIES = _descriptor.Descriptor(
  name='Movies',
  full_name='Movies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='Movies.movies', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=64,
)


_MOVIESSCHEDULES = _descriptor.Descriptor(
  name='MoviesSchedules',
  full_name='MoviesSchedules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='MoviesSchedules.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movies', full_name='MoviesSchedules.movies', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=113,
)


_EMPTYMSG = _descriptor.Descriptor(
  name='EmptyMsg',
  full_name='EmptyMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Movies'] = _MOVIES
DESCRIPTOR.message_types_by_name['MoviesSchedules'] = _MOVIESSCHEDULES
DESCRIPTOR.message_types_by_name['EmptyMsg'] = _EMPTYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

Movies = _reflection.GeneratedProtocolMessageType('Movies', (_message.Message,), {
  'DESCRIPTOR' : _MOVIES,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Movies)
  })
_sym_db.RegisterMessage(Movies)

MoviesSchedules = _reflection.GeneratedProtocolMessageType('MoviesSchedules', (_message.Message,), {
  'DESCRIPTOR' : _MOVIESSCHEDULES,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:MoviesSchedules)
  })
_sym_db.RegisterMessage(MoviesSchedules)

EmptyMsg = _reflection.GeneratedProtocolMessageType('EmptyMsg', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMSG,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMsg)
  })
_sym_db.RegisterMessage(EmptyMsg)



_SHOWTIME = _descriptor.ServiceDescriptor(
  name='Showtime',
  full_name='Showtime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=127,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetListTimes',
    full_name='Showtime.GetListTimes',
    index=0,
    containing_service=None,
    input_type=_EMPTYMSG,
    output_type=_MOVIESSCHEDULES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMovieByDate',
    full_name='Showtime.GetMovieByDate',
    index=1,
    containing_service=None,
    input_type=_DATE,
    output_type=_MOVIES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHOWTIME)

DESCRIPTOR.services_by_name['Showtime'] = _SHOWTIME

# @@protoc_insertion_point(module_scope)
